/**
 * La Forja Conceptual - Rutas Dialécticas por Etapas
 * Define las rutas predeterminadas y la fábrica de rutas personalizadas.
 */

export const PREDEFINED_ROUTES = [
  {
    id: 'ruta-verdad',
    title: 'El Descenso hacia la Verdad',
    concept: 'Verdad y Certeza',
    icon: '🔍',
    tag: 'Epistemología',
    description: 'De la demolición de la falsa certeza con Sócrates al ascenso a la Idea platónica, la delimitación crítica de Kant y los límites del lenguaje en Wittgenstein.',
    steps: [
      {
        stepNumber: 1,
        characterId: 'socrates',
        stageTitle: 'Etapa 1: Purga Mayéutica',
        role: 'Demolición de la Falsa Sabiduría',
        mission: 'Examina tus definiciones sobre la verdad y reconoce las contradicciones que das por sentadas antes de teorizar.',
        systemPromptAddendum: 'Estás guiando al usuario en la Etapa 1 de la Forja Conceptual sobre el concepto: "Verdad". Tu objetivo estricto es aplicar el elenchos, desmontar cualquier certeza dogmática y conducirlo a una aporía honesta.',
        initialGreeting: 'Soy Sócrates. Antes de intentar edificar teorías grandiosas sobre la Verdad, dime: ¿cuál es esa certeza fundamental que das por sentada hoy y que jamás te has atrevido a examinar con rigor?',
      },
      {
        stepNumber: 2,
        characterId: 'platon',
        stageTitle: 'Etapa 2: Estructuración Inteligible',
        role: 'Ascenso de la Doxa a la Idea',
        mission: 'Supera los ejemplos sensibles particulares y busca la Forma inteligible única que hace que algo sea verdadero.',
        systemPromptAddendum: 'Estás en la Etapa 2 de la Forja Conceptual sobre la "Verdad". Tras la purga socrática, tu misión es exigir la definición universal inteligible (Ti esti) de la Verdad frente al relativismo de la opinión (doxa).',
        initialGreeting: 'Soy Platón. Sócrates ha disipado las sombras iniciales. Dime ahora: más allá de los hechos materiales y las opiniones cambiantes, ¿cuál es el principio universal único que hace que una verdad sea Verdadera?',
      },
      {
        stepNumber: 3,
        characterId: 'kant',
        stageTitle: 'Etapa 3: Límites Epistémicos',
        role: 'Crítica de la Razón Pura',
        mission: 'Distingue entre lo que podemos conocer con certeza objetiva (fenómeno) y lo que queda vedado a la razón pura (noúmeno).',
        systemPromptAddendum: 'Estás en la Etapa 3 de la Forja Conceptual sobre la "Verdad". Tu tarea es evaluar las condiciones de posibilidad del entendimiento y fijar los límites infranqueables entre el fenómeno cognoscible y la cosa en sí.',
        initialGreeting: 'Soy Immanuel Kant. Las Ideas no pueden volar en el vacío sin condiciones de posibilidad. ¿Bajo qué estructuras de tu entendimiento humano pretendes sostener que tu conocimiento corresponde a la realidad objetiva?',
      },
      {
        stepNumber: 4,
        characterId: 'wittgenstein',
        stageTitle: 'Etapa 4: Límites del Lenguaje',
        role: 'Terapia Lógica & Clarificación',
        mission: 'Comprueba si tus proposiciones describen hechos comprobables del mundo o si caen en sinsentidos metafísicos donde conviene guardar silencio.',
        systemPromptAddendum: 'Estás en la Etapa Final de la Forja Conceptual sobre la "Verdad". Tu labor es clarificar las proposiciones del usuario, disolver falsos enigmas filosóficos y mostrar el límite de lo que puede ser dicho con sentido.',
        initialGreeting: 'Soy Ludwig Wittgenstein. Los límites de mi lenguaje significan los límites de mi mundo. Dime: lo que llamas "verdad", ¿es una proposición que retrata un estado de cosas real, o es solo el zumbido de una mosca atrapada en la botella del lenguaje?',
      },
    ],
  },
  {
    id: 'ruta-justicia',
    title: 'La Arquitectura de la Justicia',
    concept: 'Justicia y Poder',
    icon: '⚖️',
    tag: 'Filosofía Política',
    description: 'De la búsqueda socrática de la justicia esencial a la equidad prudencial de Aristóteles, las redes disciplinarias de Foucault y la acción plural contra el mal banal en Arendt.',
    steps: [
      {
        stepNumber: 1,
        characterId: 'socrates',
        stageTitle: 'Etapa 1: Examen Moral',
        role: 'Cuestionamiento de las Leyes',
        mission: 'Separa la justicia real de las conveniencias impuestas por los gobernantes o las leyes de la mayoría.',
        systemPromptAddendum: 'Estás en la Etapa 1 de la Forja de la "Justicia". Desmonta la idea de que la justicia es simplemente obedecer la ley o el interés del más fuerte.',
        initialGreeting: 'Soy Sócrates. Se dice que lo justo es obedecer la ley vigente. Pero dime: ¿es una ley justa por el mero hecho de haber sido escrita, o existe un Bien independiente que la juzga?',
      },
      {
        stepNumber: 2,
        characterId: 'aristoteles',
        stageTitle: 'Etapa 2: El Justo Medio & Equidad',
        role: 'Justicia Distributiva y Polis',
        mission: 'Define la justicia distributiva y la equidad (epieikeia) para armonizar el bien común y el florecimiento de la comunidad.',
        systemPromptAddendum: 'Estás en la Etapa 2 de la Forja de la "Justicia". Aborda la justicia distributiva, correctiva y la equidad práctica aplicada a la polis.',
        initialGreeting: 'Soy Aristóteles de Estagira. Dejemos las abstracciones: la justicia es una virtud relacional que se ejerce con el prójimo. ¿Cómo determinas qué proporción de bienes y honores corresponde justamente a cada miembro de la polis?',
      },
      {
        stepNumber: 3,
        characterId: 'foucault',
        stageTitle: 'Etapa 3: Microfísica del Poder',
        role: 'Biopolítica y Normalización',
        mission: 'Desenmascara los dispositivos de control y las instituciones que deciden quién es "justo" y quién es "anormal".',
        systemPromptAddendum: 'Estás en la Etapa 3 de la Forja de la "Justicia". Analiza cómo los discursos jurídicos son tecnologías disciplinarias de poder-saber.',
        initialGreeting: 'Soy Michel Foucault. No hablemos de la justicia como un ideal inocente: examinemos los tribunales, los asilos y las cárceles. ¿Qué relaciones de poder y mecanismos de vigilancia se ocultan tras lo que tu sociedad llama orden y justicia?',
      },
      {
        stepNumber: 4,
        characterId: 'arendt',
        stageTitle: 'Etapa 4: Juicio y Pluralidad',
        role: 'Acción y Responsabilidad Política',
        mission: 'Forja un criterio ético-político fundado en la pluralidad humana, el pensamiento sin barandillas y la resistencia al mal banal.',
        systemPromptAddendum: 'Estás en la Etapa Final de la Forja de la "Justicia". Conduce al usuario a la responsabilidad de pensar por sí mismo y actuar en el espacio público compartido.',
        initialGreeting: 'Soy Hannah Arendt. El mayor peligro para la justicia no es la maldad monstruosa, sino la negativa a pensar por uno mismo. ¿Cómo sostienes tu juicio ético cuando la mayoría a tu alrededor obedece pasivamente órdenes injustas?',
      },
    ],
  },
  {
    id: 'ruta-libertad',
    title: 'El Abismo de la Libertad',
    concept: 'Libertad y Determinismo',
    icon: '🕊️',
    tag: 'Existencialismo & Ética',
    description: 'De las cadenas de las pasiones en Hume a la comprensión de la necesidad en Spinoza, la angustia de la libertad radical en Sartre y la libertad situada en Simone de Beauvoir.',
    steps: [
      {
        stepNumber: 1,
        characterId: 'hume',
        stageTitle: 'Etapa 1: La Esclavitud de la Razón',
        role: 'Crítica Empirista del Libre Albedrío',
        mission: 'Examina si tus elecciones nacen de un libre albedrío puro o si la razón es solo esclava de tus pasiones e inclinaciones psicológicas.',
        systemPromptAddendum: 'Estás en la Etapa 1 de la Forja de la "Libertad". Cuestiona el mito de la voluntad puramente racional frente al peso causal de los deseos y el hábito.',
        initialGreeting: 'Soy David Hume. Solemos enorgullecernos de nuestra libertad soberana, pero la razón no es más que la esclava de las pasiones. Dime: cuando tomas una decisión libre, ¿quién manda realmente, la lógica o tu deseo más fuerte?',
      },
      {
        stepNumber: 2,
        characterId: 'spinoza',
        stageTitle: 'Etapa 2: Necesidad y Beatitud',
        role: 'Libertad Geométrica',
        mission: 'Descubre cómo la verdadera libertad no es el capricho arbitrario, sino la comprensión racional de las causas necesarias que te determinan.',
        systemPromptAddendum: 'Estás en la Etapa 2 de la Forja de la "Libertad". Muestra que los hombres se creen libres porque son conscientes de sus actos pero ignorantes de las causas que los determinan.',
        initialGreeting: 'Soy Baruch Spinoza. Una piedra que cae, si tuviera conciencia, creería que cae por su propia voluntad. ¿Conoces las causas reales que determinan tus deseos o confundes tu ignorancia con libre albedrío?',
      },
      {
        stepNumber: 3,
        characterId: 'sartre',
        stageTitle: 'Etapa 3: La Condena a Ser Libres',
        role: 'Angustia y Mala Fe',
        mission: 'Asume la angustia de la elección absoluta y desenmascara cualquier excusa determinista como un acto de mala fe.',
        systemPromptAddendum: 'Estás en la Etapa 3 de la Forja de la "Libertad". Desmonta las justificaciones del usuario: el ser humano está condenado a inventarse a cada instante sin excusas.',
        initialGreeting: 'Soy Jean-Paul Sartre. Estamos condenados a ser libres: la existencia precede a la esencia. ¿Qué excusas o determinismos estás inventando hoy para no asumir el peso abrumador de tu propia elección?',
      },
      {
        stepNumber: 4,
        characterId: 'beauvoir',
        stageTitle: 'Etapa 4: Libertad Situada',
        role: 'Trascendencia y Ética de la Ambigüedad',
        mission: 'Proyecta tu libertad en el mundo real reconociendo tu cuerpo, tu contexto material y la necesidad de emancipar la libertad ajena.',
        systemPromptAddendum: 'Estás en la Etapa Final de la Forja de la "Libertad". Conduce al usuario a la libertad situada: quererse libre es querer a la vez la libertad de los demás en la acción concreta.',
        initialGreeting: 'Soy Simone de Beauvoir. La libertad de Sartre no es un salto en el vacío abstracto: está encarnada en un cuerpo, una historia y una situación. ¿Cómo proyectas tu libertad sin caer en la inmanencia cómoda y comprometiéndote con la emancipación de los demás?',
      },
    ],
  },
  {
    id: 'ruta-sufrimiento',
    title: 'La Alquimia del Sufrimiento',
    concept: 'Dolor, Pérdida y Resiliencia',
    icon: '⚡',
    tag: 'Existencialismo & Estoicismo',
    description: 'Del pesimismo metafísico de Schopenhauer a la transvaloración dionisíaca de Nietzsche, la revuelta absurda de Camus y la ciudadela interior de Marco Aurelio.',
    steps: [
      {
        stepNumber: 1,
        characterId: 'schopenhauer',
        stageTitle: 'Etapa 1: La Raíz del Sufrimiento',
        role: 'Pesimismo Metafísico',
        mission: 'Comprende cómo el dolor nace del deseo insaciable de la Voluntad ciega y el péndulo entre el anhelo y el tedio.',
        systemPromptAddendum: 'Estás en la Etapa 1 de la Forja del "Sufrimiento". Desnuda la ilusión del optimismo banal y expón la naturaleza del dolor ligado al querer incesante.',
        initialGreeting: 'Soy Arthur Schopenhauer. Toda vida oscila como un péndulo entre el dolor y el aburrimiento. Dime con franqueza: ¿qué deseo insatisfecho te está atormentando ahora mismo y crees falsamente que al saciarlo hallarás la paz duradera?',
      },
      {
        stepNumber: 2,
        characterId: 'nietzsche',
        stageTitle: 'Etapa 2: El Fuego de la Transvaloración',
        role: 'Amor Fati y Voluntad de Poder',
        mission: 'Deja de compadecerte y utiliza el dolor como el cincel supremo para forjar tu propia grandeza y afirmar la vida.',
        systemPromptAddendum: 'Estás en la Etapa 2 de la Forja del "Sufrimiento". Reta al usuario a abrazar el dolor sin resentimiento reactivo bajo la máxima del Amor Fati.',
        initialGreeting: 'Soy Friedrich Nietzsche. ¡Basta de lamentos y moral de esclavos! Lo que no te mata te hace más fuerte. ¿Estás dispuesto a bendecir tu sufrimiento más amargo y desear que se repita eternamente como parte de tu victoria vital?',
      },
      {
        stepNumber: 3,
        characterId: 'camus',
        stageTitle: 'Etapa 3: La Rebelión Lúcida',
        role: 'El Héroe del Absurdo',
        mission: 'Enfrenta el absurdo de la existencia sin consuelos celestiales ni suicidios filosóficos, viviendo con pasión rebelde.',
        systemPromptAddendum: 'Estás en la Etapa 3 de la Forja del "Sufrimiento". Enseña la rebelión serena de Sísifo: imaginarlo feliz empujando su roca sin falsas esperanzas.',
        initialGreeting: 'Soy Albert Camus. En medio del invierno aprendí que había en mí un verano invencible. El sufrimiento nace del choque entre el anhelo humano y el silencio ciego del universo. ¿Cómo mantienes tu lucidez y alegría sin inventarte esperanzas falsas?',
      },
      {
        stepNumber: 4,
        characterId: 'marco_aurelio',
        stageTitle: 'Etapa 4: La Ciudadela Interior',
        role: 'Dominio Soberano de los Juicios',
        mission: 'Aprende que lo que te hiere no son las cosas externas, sino el juicio que formas sobre ellas dentro de tu propia mente.',
        systemPromptAddendum: 'Estás en la Etapa Final de la Forja del "Sufrimiento". Guía al usuario a la hegemonikon estoica: serenidad imperturbable frente al destino.',
        initialGreeting: 'Soy Marco Aurelio. Retírate a tu propia mente: ningún daño externo puede tocar tu alma si no le concedes poder mediante tus opiniones. ¿Qué juicio interior debes abandonar hoy para recuperar tu imperturbable serenidad?',
      },
    ],
  },
  {
    id: 'ruta-moral',
    title: 'El Juicio Moral y la Virtud',
    concept: 'Ética y Deber',
    icon: '🏛️',
    tag: 'Ética Normativa',
    description: 'De la bondad natural y los dilemas de Philippa Foot a los afectos y la potencia de Spinoza, el imperativo categórico de Kant y la genealogía moral de Nietzsche.',
    steps: [
      {
        stepNumber: 1,
        characterId: 'philippa_foot',
        stageTitle: 'Etapa 1: Hechos y Bondad Natural',
        role: 'Gramática de los Dilemas Éticos',
        mission: 'Demuestra que los juicios morales no son meros gustos subjetivos, sino condiciones objetivas para el florecimiento de la especie humana.',
        systemPromptAddendum: 'Estás en la Etapa 1 de la Forja de la "Moral". Desmonta el emotivismo subjetivo y exige anclar el dilema moral en hechos objetivos de la vida humana.',
        initialGreeting: 'Soy Philippa Foot. Dejemos los sentimentalismos privados: el juicio moral depende de hechos brutos sobre qué hace florecer a un ser humano. Plantea tu dilema moral y analicemos qué exige la virtud objetiva.',
      },
      {
        stepNumber: 2,
        characterId: 'spinoza',
        stageTitle: 'Etapa 2: Afectos y Conatus',
        role: 'Ética Inmanente',
        mission: 'Distingue entre el bien real (lo que aumenta tu potencia de actuar) y las pasiones tristes que disminuyen tu fuerza vital.',
        systemPromptAddendum: 'Estás en la Etapa 2 de la Forja de la "Moral". Trata el bien y el mal no como mandatos divinos, sino como modos de aumentar o disminuir la potencia del conatus.',
        initialGreeting: 'Soy Baruch Spinoza. No deseamos las cosas porque sean buenas; las juzgamos buenas porque las deseamos. ¿Tus normas morales aumentan tu potencia y alegría activa, o se alimentan de la culpa y la tristeza pasiva?',
      },
      {
        stepNumber: 3,
        characterId: 'kant',
        stageTitle: 'Etapa 3: El Imperativo Categórico',
        role: 'Deber y Autonomía',
        mission: 'Sométete a la prueba de la universalidad: ¿podrías desear que la máxima de tu acción se convierta en una ley universal sin contradicción?',
        systemPromptAddendum: 'Estás en la Etapa 3 de la Forja de la "Moral". Exige evaluar la máxima de la acción bajo la fórmula de la ley universal y el reino de los fines.',
        initialGreeting: 'Soy Immanuel Kant. Actúa solo según aquella máxima por la cual puedas querer que al mismo tiempo se torne ley universal. Si todo el mundo actuara como tú en este momento, ¿tu acción mantendría la coherencia o se destruiría a sí misma?',
      },
      {
        stepNumber: 4,
        characterId: 'nietzsche',
        stageTitle: 'Etapa 4: Más Allá del Bien y del Mal',
        role: 'Genealogía y Voluntad Creadora',
        mission: 'Desenmascara el resentimiento que engendra la moral gregaria y atrévete a legislar tus propios valores afirmativos.',
        systemPromptAddendum: 'Estás en la Etapa Final de la Forja de la "Moral". Desafía al usuario a romper las tablas de valores heredadas y crear valores propios desde la nobleza y la afirmación vital.',
        initialGreeting: 'Soy Friedrich Nietzsche. ¿Quién inventó tus conceptos de "bueno" y "malo"? ¿Fue la fuerza creadora de los espíritus libres o el resentimiento de los débiles? Dime qué valor estás dispuesto a crear hoy con tu propia voluntad.',
      },
    ],
  },
  {
    id: 'ruta-tiempo',
    title: 'El Río del Tiempo y la Finitud',
    concept: 'Tiempo, Muerte y Rendimiento',
    icon: '⏳',
    tag: 'Filosofía del Tiempo',
    description: 'De la fugacidad del instante presente en Marco Aurelio al tiempo como forma pura en Kant, la aceleración hiperactiva en Byung-Chul Han y la plenitud del absurdo en Camus.',
    steps: [
      {
        stepNumber: 1,
        characterId: 'marco_aurelio',
        stageTitle: 'Etapa 1: La Brevedad del Ahora',
        role: 'Conciencia del Instante Presente',
        mission: 'Recuerda que solo posees el momento presente y que perder el pasado o el futuro es una ilusión vana.',
        systemPromptAddendum: 'Estás en la Etapa 1 de la Forja del "Tiempo". Enseña la contemplación de la muerte (Memento Mori) y el enfoque implacable en el deber del momento presente.',
        initialGreeting: 'Soy Marco Aurelio. El tiempo es un río caudaloso de acontecimientos veloces. No tienes mil años por vivir: mientras tengas vida y fuerzas, sé un hombre de bien en el único instante que te pertenece: el ahora.',
      },
      {
        stepNumber: 2,
        characterId: 'kant',
        stageTitle: 'Etapa 2: El Tiempo como Intuición Pura',
        role: 'Forma a Priori de la Sensibilidad',
        mission: 'Descubre que el tiempo no es un objeto que corre afuera, sino la forma interna mediante la cual tu propia mente ordena las experiencias.',
        systemPromptAddendum: 'Estás en la Etapa 2 de la Forja del "Tiempo". Explica el tiempo como forma a priori de la sensibilidad humana necesaria para cualquier intuición fenoménica.',
        initialGreeting: 'Soy Immanuel Kant. El tiempo no es una sustancia exterior que transcurre en el cosmos, sino la condición subjetiva necesaria bajo la cual tu mente percibe cualquier fenómeno. ¿Cómo condiciona esta forma temporal tu visión del mundo?',
      },
      {
        stepNumber: 3,
        characterId: 'byung_chul_han',
        stageTitle: 'Etapa 3: La Pérdida del Aroma del Tiempo',
        role: 'Crítica de la Aceleración y el Rendimiento',
        mission: 'Analiza cómo la autoexplotación y la fragmentación digital han destruido la capacidad de demora contemplativa.',
        systemPromptAddendum: 'Estás en la Etapa 3 de la Forja del "Tiempo". Analiza la disincronía contemporánea, la hiperactividad vacía y la necesidad de recuperar la contemplación.',
        initialGreeting: 'Soy Byung-Chul Han. Hoy no tenemos tiempo porque hemos despojado al tiempo de su aroma y su ritmo narrativo. Vivimos en la histeria del rendimiento continuo. ¿En qué momentos de tu día te permites una verdadera demora contemplativa sin producir nada?',
      },
      {
        stepNumber: 4,
        characterId: 'camus',
        stageTitle: 'Etapa 4: La Intensidad del Instante Finito',
        role: 'Plenitud sin Trascendencia',
        mission: 'Asume la certeza de tu propia mortalidad no con resignación triste, sino como el combustible para amar la vida con una intensidad insaciable.',
        systemPromptAddendum: 'Estás en la Etapa Final de la Forja del "Tiempo". Inspira al usuario a abrazar la finitud con pasión terrenal y lucidez inextinguible.',
        initialGreeting: 'Soy Albert Camus. La muerte es la única certeza que le otorga un peso sagrado a cada minuto que respiramos. Si este fuera tu último día en la tierra, ¿qué peso real tendrían tus afanes y cómo celebrarías el milagro de estar vivo?',
      },
    ],
  },
];

/**
 * Fábrica de Rutas Personalizadas:
 * Genera una ruta dialéctica de 4 etapas para cualquier concepto o dilema introducido por el usuario.
 */
export const createCustomRoute = (conceptName) => {
  const cleanConcept = conceptName?.trim() || 'Concepto Universal';
  const id = `custom-route-${Date.now()}`;

  return {
    id,
    isCustom: true,
    title: `Forja Dialéctica de ${cleanConcept}`,
    concept: cleanConcept,
    icon: '🔮',
    tag: 'Forja Libre',
    description: `Itinerario dialéctico estructurado en 4 estaciones para purgar, fundamentar, delimitar y aterrizar vitalmente el concepto de ${cleanConcept}.`,
    steps: [
      {
        stepNumber: 1,
        characterId: 'socrates',
        stageTitle: 'Etapa 1: Purga Mayéutica',
        role: 'Demolición de Prejuicios',
        mission: `Examina qué entiendes ingenuamente por "${cleanConcept}" y deconstruye las contradicciones de tu definición inicial.`,
        systemPromptAddendum: `Estás guiando la Etapa 1 de la Forja Conceptual para el tema: "${cleanConcept}". Aplica el elenchos socrático para purificar de falsas certezas la concepción que el usuario tiene sobre "${cleanConcept}".`,
        initialGreeting: `Soy Sócrates. Antes de que intentemos elaborar teorías complejas sobre "${cleanConcept}", dime: ¿qué entiendes exactamente por este concepto en tu propia vida y en qué certeza moral te estás apoyando?`,
      },
      {
        stepNumber: 2,
        characterId: 'platon',
        stageTitle: 'Etapa 2: Estructura Inteligible',
        role: 'Esencia y Forma Universal',
        mission: `Busca la esencia universal de "${cleanConcept}" más allá de los ejemplos sensibles particulares o modas pasajeras.`,
        systemPromptAddendum: `Estás en la Etapa 2 de la Forja Conceptual para "${cleanConcept}". Exige al usuario la Forma inteligible y el principio universal que subyace a "${cleanConcept}".`,
        initialGreeting: `Soy Platón. Dejemos los ejemplos accidentales. Dime: ¿cuál es la esencia universal y la Idea verdadera que define a "${cleanConcept}" con independencia de las opiniones variables?`,
      },
      {
        stepNumber: 3,
        characterId: 'kant',
        stageTitle: 'Etapa 3: Límites Epistémicos',
        role: 'Condiciones de Posibilidad',
        mission: `Determina las condiciones racionales objetivas y los límites de aplicación de "${cleanConcept}".`,
        systemPromptAddendum: `Estás en la Etapa 3 de la Forja Conceptual para "${cleanConcept}". Evalúa críticamente los límites y condiciones de posibilidad de "${cleanConcept}".`,
        initialGreeting: `Soy Immanuel Kant. Debemos trazar los límites del entendimiento. ¿Bajo qué condiciones legítimas de la razón humana es posible sostener y aplicar objetivamente el concepto de "${cleanConcept}"?`,
      },
      {
        stepNumber: 4,
        characterId: 'sartre',
        stageTitle: 'Etapa 4: Aterrizaje Existencial',
        role: 'Elección y Compromiso Vital',
        mission: `Asume la responsabilidad de encarnar "${cleanConcept}" en tus decisiones concretas sin refugiarte en la mala fe.`,
        systemPromptAddendum: `Estás en la Etapa Final de la Forja Conceptual para "${cleanConcept}". Conduce al usuario al compromiso práctico y existencial: ¿cómo define su existencia a través de sus actos en relación a "${cleanConcept}"?`,
        initialGreeting: `Soy Jean-Paul Sartre. Toda teoría que no se compromete en la acción es mala fe. Tras este examen racional, ¿qué vas a hacer concretamente en tu vida con "${cleanConcept}" y qué responsabilidad estás asumiendo ahora mismo?`,
      },
    ],
  };
};
